### ISSUE TITLE
Create a command line tool to manage settings

### ISSUE THREAD

**Issue by marcpage** [marcpage/devops-driver#57]
In Issue #47 we had a warning generated when we promoted components that used settings to the top level of `devopsdriver` in `__init__.py`. 

We should create a new script that includes `devopsdriver.settings` and contains the command line tool code that currently resides in `settings.py`. 

When we do, we should add a command line tool:

```toml
[project.scripts]
settings = "devopsdriver:manage_settings"
```
